server:
  port: 8888


  #Config Repo
spring:
  cloud:
    config:
      server:
        git:
          uri:  file:///C:/Users/KAVUR/Desktop/config-server/New folder/config-repo-git

# disable security for end points
#management:
#  security:
#    enabled: false
management:
  endpoints:
    web:
      base-path: /
